<a href="https://colab.research.google.com/github/arunangshudutta/EE5121_assignment_2/blob/main/Prob_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import cvxpy as cp
import numpy as np

# Graph (i)

In [13]:
G_edges = [(1,2),(1,3),(1,4),(2,3),(2,4),(3,4)]
n = 4

E = [(u-1, v-1) for (u, v) in G_edges]

In [14]:
# Primal problem solver

# Variables
G = cp.Variable((n, n), symmetric=True)
rho = cp.Variable()

constraints = []

# PSD constraint
constraints += [G >> 0]

# Diagonal = 1
for v in range(n):
    constraints += [G[v, v] == 1]

# Edge constraints G_uv <= rho
for (u, v) in E:
    constraints += [G[u, v] <= rho]

# Objective
objective = cp.Minimize(rho)

prob = cp.Problem(objective, constraints)
prob.solve(solver=cp.SCS, verbose=False)

print("==== PRIMAL ====")
print("rho* =", rho.value)
print("G* =")
print(G.value)
print("Primal function optimum value rho =", rho.value)

==== PRIMAL ====
rho* = -0.33333333255748676
G* =
[[ 1.         -0.33333333 -0.33333333 -0.33333333]
 [-0.33333333  1.         -0.33333333 -0.33333333]
 [-0.33333333 -0.33333333  1.         -0.33333333]
 [-0.33333333 -0.33333333 -0.33333333  1.        ]]
Primal function optimum value rho = -0.33333333255748676


In [15]:
# Dual problem solver
m = len(E)

# Dual variables
lam = cp.Variable(n)
alpha = cp.Variable(m, nonneg=True)    # α_uv >= 0

# Construct S
S = cp.Variable((n, n), symmetric=True)

constraints = []

# S = diag(lam) + Σ α_uv (E_uv + E_vu)
expr = cp.diag(lam)

for idx, (u, v) in enumerate(E):
    A = np.zeros((n, n))
    A[u, v] = 1
    A[v, u] = 1
    expr += alpha[idx] * A

constraints += [S == expr]

# sum α_uv = 1
constraints += [cp.sum(alpha) == 1]

# PSD constraint
constraints += [S >> 0]

# Objective: maximize  -sum(lam)
objective = cp.Maximize(-cp.sum(lam))

prob = cp.Problem(objective, constraints)
prob.solve(solver=cp.SCS, verbose=False)

print("==== DUAL ====")
print("Dual optimum function value =")
print(-np.sum(lam.value))

==== DUAL ====
Dual optimum function value =
-0.6666666667363965


In [16]:
print("Duality Gap =", abs(-np.sum(lam.value) - rho.value))

Duality Gap = 0.33333333417890976


# Graph (ii)

In [17]:
G_edges = [(1,2), (2,3), (3,4), (4,5), (5,1)]
n = 5

E = [(u-1, v-1) for (u, v) in G_edges]


In [18]:
# Primal problem solver

# Variables
G = cp.Variable((n, n), symmetric=True)
rho = cp.Variable()

constraints = []

# PSD constraint
constraints += [G >> 0]

# Diagonal = 1
for v in range(n):
    constraints += [G[v, v] == 1]



# Edge constraints G_uv <= rho
for (u, v) in E:
    constraints += [G[u, v] <= rho]

# Objective
objective = cp.Minimize(rho)

prob = cp.Problem(objective, constraints)
prob.solve(solver=cp.SCS, verbose=False)

print("==== PRIMAL ====")
print("Primal function optimum value rho* =", rho.value)

==== PRIMAL ====
Primal function optimum value rho* = -0.8090172334287339


In [19]:
# Dual problem solver
m = len(E)

# Dual variables
lam = cp.Variable(n)
alpha = cp.Variable(m, nonneg=True)    # α_uv >= 0

# Construct S
S = cp.Variable((n, n), symmetric=True)

constraints = []

# S = diag(lam) + Σ α_uv (E_uv + E_vu)
expr = cp.diag(lam)

for idx, (u, v) in enumerate(E):
    A = np.zeros((n, n))
    A[u, v] = 1
    A[v, u] = 1
    expr += alpha[idx] * A

constraints += [S == expr]

# sum α_uv = 1
constraints += [cp.sum(alpha) == 1]

# PSD constraint
constraints += [S >> 0]

# Objective: maximize  -sum(lam)
objective = cp.Maximize(-cp.sum(lam))

prob = cp.Problem(objective, constraints)
prob.solve(solver=cp.SCS, verbose=False)

print("==== DUAL ====")
print("Dual optimum function value =")
print(-np.sum(lam.value))

==== DUAL ====
Dual optimum function value =
-1.6180339890799083


In [20]:
print("Duality Gap =", abs(-np.sum(lam.value) - rho.value))

Duality Gap = 0.8090167556511744
